#!/usr/bin/tcsh 
cd src
pwd
make clean
make
echo "run mc_single_arm"
./mc_single_arm << endofinput >! ../runout/$1.out
$1
endofinput
cd ../util/root_tree
make clean
make
./make_root_tree << endofinput
$1
endofinput
cd ../..
rm worksim/$1.bin
