#!/usr/bin/tcsh 

module purge
module use /cvmfs/oasis.opensciencegrid.org/jlab/scicomp/sw/el9/modulefiles
module load root/6.30.04-gcc11.4.0

cd src
make clean
make
./mc_single_arm <<EOF |& tee "../runout/$1.out"
$1
EOF
cd ../util/root_tree
make clean
make
./make_root_tree << endofinput
$1
endofinput
cd ../..
rm -f worksim/$1.bin
# mv worksim/$1.root outfiles/
